// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nyhetssajt.Models;

namespace Nyhetssajt.Migrations
{
    [DbContext(typeof(ExpressenContext))]
    partial class ExpressenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nyhetssajt.Models.Expressen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("description");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("pubDate")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Expressens");
                });
#pragma warning restore 612, 618
        }
    }
}
