// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nyhetssajt.Models;

namespace Nyhetssajt.Migrations.Svd
{
    [DbContext(typeof(SvdContext))]
    [Migration("20190818091208_RemovedCharSize")]
    partial class RemovedCharSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nyhetssajt.Models.Svd", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ID");

                    b.ToTable("Svds");
                });
#pragma warning restore 612, 618
        }
    }
}
